
title: My Resume
url: 'Davdegreat.github.io'
baseurl: '/MyPanelCV' #change it according to your repository name



# Profile information
yourname: David Dilanchian  ## put your name
title: 'Entrepreneur & Developer '  ## your title
location: Montreal, CA


## Social Profiles
## facebook: http://www.facebook.com  ## your facebook account url
## twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/david-dilanchian/  ## your linkedin account url
## dribbble: http://www.dribble.com  ## you dribbble account url
## foursquare: http://www.foursquare.com  ## your foursquare account url
github: https://github.io/david-dilan


# Update all the sections by editing the files inside _includes folder.
